_target_: gfmrag.text_emb_models.BaseTextEmbModel
text_emb_model_name: Alibaba-NLP/gte-Qwen2-1.5B-instruct
normalize: False
batch_size: 32
query_instruct: "Instruct: Given a web search query, retrieve relevant passages that answer the query\nQuery: "
passage_instruct: null
model_kwargs: null
