_target_: gfmrag.text_emb_models.NVEmbedV2
text_emb_model_name: nvidia/NV-Embed-v2
normalize: True
batch_size: 1
query_instruct: "Instruct: Given a multi-hop question, retrieve documents that can help answer the question\nQuery: "
passage_instruct: ""
model_kwargs:
  torch_dtype: bfloat16
