_target_: gfmrag.text_emb_models.Qwen3TextEmbModel
text_emb_model_name: Qwen/Qwen3-Embedding-8B
normalize: True
batch_size: 32
query_instruct: "Instruct: Given a web search query, retrieve relevant passages that answer the query\nQuery: "
passage_instruct: null
truncate_dim: 4096
