_target_: gfmrag.graph_index_construction.graph_constructors.KGConstructor # The KGConstructor class
open_ie_model: ${openie_model}
el_model: ${el_model}
root: tmp/kg_construction # Temporary directory for storing intermediate files during KG construction
num_processes: 10 # Number of processes to use
cosine_sim_edges: True # Whether to conduct entities resolution using cosine similarity
threshold: 0.8 # Threshold for cosine similarity
max_sim_neighbors: 100 # Maximum number of similar neighbors to add
add_title: True # Whether to add the title to the content of the document during OpenIE
force: False # Whether to force recompute the KG
