hydra:
  run:
    dir: outputs/qa_finetune/${now:%Y-%m-%d}/${now:%H-%M-%S} # Output directory
  searchpath:
    - pkg://gfmrag.workflow.config

defaults:
  - _self_
  - text_emb_model: qwen3 # The text embedding model to use
  - wandb: default # Weights & Biases configuration

seed: 1024
timeout: 60 # timeout minutes for multi-gpu training
save_pretrained: no # Save the model in pre-trained format
load_model_from_pretrained: null # Load model from pre-trained format, which would overwrite the model configuration

datasets:
  _target_: gfmrag.graph_index_datasets.GraphIndexDataset # The QA dataset class
  cfgs:
    root: ./data # data root directory
    force_reload: False # Whether to force rebuild the dataset
    text_emb_model_cfgs: ${text_emb_model} # The text embedding model configuration
  train_names: # List of training dataset names
    - hotpotqa_train_example
  valid_names: # List of validation dataset names
    - hotpotqa_test
    - hotpotqa_test_v2
    - musique_test
    - 2wikimultihopqa_test
  init_datasets: True # Whether to pre-process datasets at the beginning, if true, it will pre-process all datasets in the train_names and valid_names at the beginning
  feat_dim: 1024 # Feature dimension for the embeddings, must be given if init_datasets is False
  max_datasets_in_memory: 10 # Number of datasets to load into memory at once
  data_loading_workers: 4 # Number of workers for data loading

# GFM model configuration
model:
  _target_: gfmrag.models.gfm_reasoner.GraphReasoner
  use_ent_emb: early-late-fusion
  # Mixed precision training configuration
  dtype: bfloat16 # Precision type: 'float32', 'float16', 'bfloat16', or 'auto'
  entity_model:
    _target_: gfmrag.models.ultra.models.QueryNBFNet
    input_dim: 1024
    hidden_dims: [1024, 1024, 1024, 1024, 1024, 1024]
    message_func: distmult
    aggregate_func: sum
    short_cut: yes
    layer_norm: yes
    return_hidden: True # Return the hidden states of the entity model

# Loss configuration
losses:
  - name: bce_loss
    loss:
      _target_: gfmrag.losses.BCELoss
      adversarial_temperature: 0.2
    weight: 0.3
    target_node_type: document
  - name: pcr_loss
    loss:
      _target_: gfmrag.losses.ListCELoss
    weight: 0.7
    target_node_type: document
  - name: mse_loss
    loss:
      _target_: gfmrag.losses.MSELoss
    weight: 1
    target_node_type: document
    is_distillation_loss: True
  # - name: kl_loss
  #   loss:
  #     _target_: gfmrag.losses.KLDivLoss
  #   weight: 0.01
  #   target_node_type: document
  #   is_distillation_loss: True

# Optimizer configuration
optimizer:
  _target_: torch.optim.AdamW
  lr: 5.0e-4

# Training configuration
trainer:
  _target_: gfmrag.trainers.SFTTrainer
  args:
    _target_: gfmrag.trainers.TrainingArguments
    train_batch_size: 8
    num_epoch: 20
    logging_steps: 100
    max_steps_per_epoch: null
    resume_from_checkpoint: null
    do_train: true
    do_eval: true
    save_best_only: yes
    metric_for_best_model: document_mrr
    dtype: ${model.dtype} # Use the same precision type
    split_graph_inference: false
    split_graph_training: false
    split_graph_partition: contiguous  # contiguous or metis
  metrics: [mrr, hits@1, hits@2, hits@3, hits@5, hits@10, hits@20, recall@2, recall@3, recall@5, recall@10, recall@20] # List of metrics to calculate
  target_types: [document] # The target node types used for metric calculation
