hydra:
  run:
    dir: outputs/experiments/visualize/${dataset.data_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  searchpath:
    - pkg://gfmrag.workflow.config

defaults:
  - _self_

timeout: 60
seed: 1024

load_model_from_pretrained: null # Load model from pre-trained format, which would overwrite the model configuration

dataset:
  _target_: gfmrag.graph_index_datasets.GraphIndexDataset # The QA dataset class
  data_name: hotpotqa_test_v2
  root: ./data # data root directory
  force_reload: False # Whether to force rebuild the dataset

test_max_sample: 100
